#!/usr/bin/env python
import sys

import easywatch
from fabric.api import local, settings


def main(argv):
    """Watch the current directory and run argv[1] on change."""
    def handler(event_type, src_path):
        if event_type == "modified":
            with settings(warn_only=True):
                local(argv[1])
    easywatch.watch(".", handler)


if __name__ == "__main__":
    main(sys.argv)
